cookie:
  expiry_days: 30
  key: random_signature_key
  name: random_cookie_name
credentials:
  usernames:
    admin_user:
      email: pchichghare@synoptek.com
      name: Admin User
      otp_secret: null
      password: $2b$12$Hr2fVKb8tbUeOvsILEFGTuqSmBR4r0ZkexsJknT3qCSqv.qfnG4Le
    apurohit:
      email: apurohit@synoptek.com
      name: Anish Purohit
      otp_secret: null
      password: 2b$12$bWQsVhtm/Wj1Z7Hz/j8BL.jvfkaRH8guvKU0oFF58RztK4lfsWDaK
    bbray:
      email: bbray@synoptek.com
      name: Bo Bray
      otp_secret: null
      password: $2b$12$35BcfMDeNb5MGKS3tTNe3OiSsnC0EJCexYEpjiJ6scV24wLTepBDKcd ..
    cmccarthy:
      email: cmccarthy@synoptek.com
      name: Christopher McCarthy
      otp_secret: null
      password: $2b$12$8kgaw8oFHJ2Fz.RDSVY1NO0xBIQc4rHfhtdRkT55HEy2I2Wm160RO
    gfenton:
      email: gfenton@synoptek.com
      name: George Fenton
      otp_secret: null
      password: $2b$12$2mR2UBOiEvCk7TJz4s1GceMbABKebEw/IBbU3vbwXlgG1CZZkBw.O
    gwarhus:
      email: gwarhus@synoptek.com
      name: Giselle Warhus
      otp_secret: null
      password: $2b$12$JwnkfsQWLBRYUoYM8FIFreIMHpt6fBmdPChL/VoO78ZtUPGTJ45zW
    jcann:
      email: jcann@synoptek.com
      name: Jay Cann
      otp_secret: null
      password: $2b$12$wu3hwmyJCP5o1G8PGZu3V.DC3nW27dhudTJpISrym5hllbRarSVzq
    jvanni:
      email: jvanni@synoptek.com
      name: John Vanni
      otp_secret: null
      password: $2b$12$wgWZUD3z.15c.IIbD6jNyOFbPG7S7NPUc5L6QxmoZvoTnp1kOUsG2
    msanchez:
      email: msanchez@synoptek.com
      name: Miguel Sanchez
      otp_secret: null
      password: $2b$12$maBqZsf4MyKvDR0ThQ0F5OrVMUCPMveUprjbXCFXDZpAU96dYT.Va
    mthakkar:
      email: mthakkar@synoptek.com
      name: Manan Thakkar
      otp_secret: null
      password: $2b$12$0RT1iEN9xpvcCUg.knjBwexdU6uyUSSbBm2i.3fgzyOWwJzRRx3Ri
    nasingh:
      email: nasingh@synoptek.com
      name: Naman Singh
      otp_secret: null
      password: $2b$12$DENNIOBrJee7Gd8GjOZo.Orh4VmV7kqu1Jo.iZ27rFFgF6ozxz1CW
    rroger:
      email: rroger@synoptek.com
      name: Rohan Roger
      otp_secret: null
      password: $2b$12$N4KgbJblRf9.rdjRFmMiMeCP5cjNI5RbG0rUmmTETqrJC1nzHoY6u
    sgahlot:
      email: sgahlot@synoptek.com
      name: Shubhankar Gahlot
      otp_secret: null
      password: $2b$12$xW4QYaa8e1acHvWgTekQ6OrkA1CMcA0DHCcn.A7uaIAja.oRZJ1Jq
    sryan:
      email: sryan@synoptek.com
      name: Sean Ryan
      otp_secret: null
      password: $2b$12$vhSUK6STSp/vr6D1Lt/Wx.XrsgQLics.EQASpTNl0eIA3euEx5R1y
    tbritt:
      email: tbritt@synoptek.com
      name: Timothy Britt
      otp_secret: null
      password: $2b$12$J9FC4rE8GzqZTiNf4TViI.MInsnwlf3PKCOhENETU3DHUMUfp.Dc6
    mfeinberg:
      email: mfeinberg@synoptek.com
      name: Miles Feinberg
      otp_secret: null
      password: $2b$12$MsLPHeRC69wkF3MnI48VM.7a9ITzXdpK8PPXcHmFX0qmjHocyEb8O
    test_user:
      email: pchichghare@synoptek.com
      name: Test User
      otp_secret: A7ST74VOMAGBG45I7NEBC7R6SK2MW5HC
      password: $2b$12$SqNoNX8fRpxNn6waMVPSx.s4GIUzrqEracZ8cYGQGWyLF4eoTPJhi
